import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'
const fixture = name => JSON.parse(readFileSync(new URL(`../fixtures/${name}.json`, import.meta.url), 'utf8'))
const summary = fixture('live-mlb')
async function setup(page, { live = false, spoiler = false } = {}) {
  await page.setViewportSize({width:390,height:844})
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.clock.setFixedTime(new Date('2026-09-18T17:00:00Z'))
  if (spoiler) await page.addInitScript(() => localStorage.setItem('cs.fan.v1', JSON.stringify({spoiler:true})))
  let final = !live
  const data = () => {
    const result = structuredClone(summary)
    result.header.competitions[0].status.type = {state: final ? 'post':'in', completed:final, shortDetail:final ? 'Final':'Bottom 7th'}
    result.situation = { balls:2,strikes:1,outs:1,onFirst:true,onSecond:false,pitchCount:65 }
    return result
  }
  await page.route('**/espn/**', route => {
    const url = new URL(route.request().url())
    if (url.pathname.endsWith('/summary')) return route.fulfill({json:data()})
    if (url.pathname.endsWith('/news')) return route.fulfill({json:{articles:[
      {id:1,headline:'Sox story from ESPN',published:'2026-09-18T12:00:00Z',categories:[{type:'team',teamId:4,description:'Chicago White Sox'}],links:{web:{href:'https://www.espn.com/story/1'}}},
      {id:2,headline:'Unrelated club story',categories:[{type:'team',teamId:16}],links:{web:{href:'https://www.espn.com/story/2'}}},
    ]}})
    if (url.pathname.endsWith('/schedule') || url.pathname.endsWith('/scoreboard')) {
      const competition = {...data().header.competitions[0]}
      return route.fulfill({json:{season:{year:2026,type:2},events:[{id:'401816978',date:'2026-09-17T23:40:00Z',season:{year:2026,type:2},competitions:[competition]}]}})
    }
    return route.fulfill({json:{}})
  })
  await page.route('**/mlbstats/**',route=>route.fulfill({json:{dates:[]}}))
  await page.route('**/nhlweb/**',route=>route.fulfill({json:{games:[]}}))
  await page.route('**/api/**',route=>route.fulfill({json:{events:[]}}))
  return { finish:()=>{final=true} }
}
test('news filters by team, respects spoilers and opens original source links',async({page})=>{
  await setup(page,{spoiler:true})
  await page.goto('/?team=whitesox&season=2026&tab=news')
  await expect(page.getByText('Sox story from ESPN')).toHaveCount(0)
  await page.getByRole('button',{name:/Reveal news headlines/}).click()
  await expect(page.getByRole('link',{name:/Sox story/})).toHaveAttribute('href','https://www.espn.com/story/1')
  await expect(page.getByText('Unrelated club story')).toHaveCount(0)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390)
})
test('YouTube links find dated highlights and official classic footage',async({page})=>{
  await setup(page,{spoiler:true})
  await page.goto('/?team=whitesox&season=2026&tab=schedule')
  await page.getByText('Watch on YouTube',{exact:true}).click()
  const highlight=page.getByRole('link',{name:'Find highlights'})
  const query=new URL(await highlight.getAttribute('href')).searchParams.get('search_query')
  expect(query).toBe('Chicago White Sox vs Detroit Tigers September 17, 2026 highlights')
  await expect(highlight).toHaveAttribute('target','_blank')
  await expect(highlight).toHaveAttribute('rel','noopener noreferrer')
  await expect(page.getByRole('button',{name:'Reveal score',exact:true})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390)
  await page.goto('/?team=whitesox&tab=timemachine')
  await page.getByRole('button',{name:'2005',exact:true}).click()
  await page.getByRole('button',{name:/Reveal this year's history/}).click()
  const sox=page.locator('.time-club').filter({has:page.getByRole('heading',{name:'White Sox',exact:true})})
  await sox.getByText('Watch on YouTube',{exact:true}).click()
  await expect(sox.getByRole('link',{name:/Watch 2005 World Series Game 4/})).toHaveAttribute('href','https://www.youtube.com/watch?v=HaAsMEN7qbA')
})
test('lineup adds, moves, persists and restores a shared team-specific link',async({page})=>{
  await setup(page)
  await page.goto('/?team=cubs&tab=lineup')
  await page.getByLabel('Legend',{exact:true}).selectOption({label:'Ernie Banks'})
  await page.getByLabel('Position',{exact:true}).selectOption('SS')
  await page.getByRole('button',{name:'Add legend'}).click()
  await page.getByLabel('Move Ernie Banks to position').selectOption('1B')
  await expect(page.locator('.lineup-slot').filter({has:page.locator('.lineup-slot-head strong',{hasText:'1B'})})).toContainText('Ernie Banks')
  await page.reload()
  await expect(page.getByLabel('Move Ernie Banks to position')).toHaveValue('1B')
  await page.evaluate(()=> { window.shared=''; navigator.clipboard.writeText=async text=>{window.shared=text} })
  await page.getByRole('button',{name:'Share lineup'}).click()
  const link=await page.evaluate(()=>window.shared)
  expect(link).toContain('team=cubs&tab=lineup#lineup=')
  await page.evaluate(()=>localStorage.clear())
  await page.goto(link)
  await expect(page.getByLabel('Move Ernie Banks to position')).toHaveValue('1B')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(390)
})
test('stadium map works with keyboard and Time Machine opens an exact season',async({page})=>{
  await setup(page)
  await page.goto('/?team=cubs&tab=stadiums')
  const marker=page.locator('svg').getByRole('button',{name:'United Center'})
  await marker.focus(); await marker.press('Enter')
  await expect(page.locator('.stadium-detail h3')).toHaveText('United Center')
  await expect(page.locator('.stadium-detail img')).toHaveAttribute('alt','Aerial view of United Center')
  await page.getByRole('button',{name:'Time Machine',exact:true}).click()
  await page.getByRole('button',{name:'1985',exact:true}).click()
  const bears=page.locator('.time-club').filter({has:page.getByRole('heading',{name:'Bears',exact:true})})
  await expect(bears).toContainText('Championship season')
  await bears.getByRole('button',{name:'Explore season'}).click()
  await expect(page).toHaveURL(/team=bears&season=1985&tab=archive/)
})
test('replay opens without revealing spoilers and only shows final at the ending',async({page})=>{
  await setup(page,{spoiler:true})
  await page.goto('/?team=whitesox&season=2026&tab=schedule')
  await page.getByRole('button',{name:'Relive game',exact:true}).click()
  const dialog=page.getByRole('dialog',{name:'Relive this game'})
  await expect(dialog.locator('.experience-score strong')).toHaveText(['—','—'])
  await expect(dialog.getByText('Replay complete · Final')).toHaveCount(0)
  await dialog.getByRole('button',{name:'Next play',exact:true}).click()
  await expect(dialog.locator('.replay-position')).toContainText('Play 1 of')
  await dialog.getByRole('button',{name:'Jump to ending'}).click()
  await expect(dialog.locator('.experience-score strong')).toHaveText(['3','1'])
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(page.getByRole('button',{name:'Reveal score',exact:true})).toBeVisible()
})
test('Ballpark is a keyboard-safe dialog showing known and unknown game situations',async({page})=>{
  await setup(page,{live:true})
  await page.goto('/?team=whitesox&season=2026&tab=schedule&game=401816978')
  const launch=page.getByRole('button',{name:'Ballpark mode',exact:true})
  await launch.click()
  const dialog=page.getByRole('dialog',{name:'Live Ballpark'})
  await expect(dialog.getByRole('img')).toHaveAttribute('aria-label',/first base: occupied, second base: empty, third base: unavailable/)
  await expect(dialog.locator('.baseball-situation')).toContainText('65')
  await expect(dialog.locator('.ballpark-plays li')).toHaveCount(8)
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(launch).toBeFocused()
})
test('victory celebrates observed wins once and never historical finals',async({page})=>{
  const feed=await setup(page,{live:true})
  await page.goto('/?team=whitesox&season=2026&tab=schedule&game=401816978')
  await expect(page.locator('.live-status')).toHaveText('LIVE')
  await expect(page.locator('.victory-celebration')).toHaveCount(0)
  feed.finish()
  await page.locator('.live-scoreboard').getByRole('button',{name:'Refresh',exact:true}).click()
  await expect(page.locator('.victory-celebration')).toContainText('White Sox win!')
  await page.getByRole('button',{name:'Dismiss',exact:true}).click()
  await page.locator('.live-scoreboard').getByRole('button',{name:'Refresh',exact:true}).click()
  await expect(page.locator('.victory-celebration')).toHaveCount(0)
  await page.reload()
  await expect(page.locator('.live-scoreboard')).toContainText('Final')
  await expect(page.locator('.victory-celebration')).toHaveCount(0)
})
test('poster exports a real PNG and keeps hidden scores private',async({page})=>{
  await setup(page,{spoiler:true})
  await page.goto('/?team=whitesox&season=2026&tab=schedule')
  await page.getByRole('button',{name:'Make poster',exact:true}).click()
  const dialog=page.getByRole('dialog',{name:'Make a game poster'})
  await dialog.getByLabel('Caption',{exact:true}).fill('A night on the South Side')
  await expect(dialog.getByLabel('Include score')).toBeDisabled()
  await expect(dialog.getByRole('img')).toHaveAttribute('aria-label',/Scores hidden/)
  const downloadPromise=page.waitForEvent('download')
  await dialog.getByRole('button',{name:'Download PNG'}).click()
  const download=await downloadPromise
  const bytes=readFileSync(await download.path())
  expect(bytes.subarray(0,8).toString('hex')).toBe('89504e470d0a1a0a')
  expect(bytes.readUInt32BE(16)).toBe(1080);expect(bytes.readUInt32BE(20)).toBe(1350)
  expect(bytes.length).toBeGreaterThan(10000)
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
})
