import { readFileSync } from 'node:fs'
import { test, expect } from '@playwright/test'
import { dailyQuestion } from '../../src/arcade.js'

const fixture = (name) => JSON.parse(readFileSync(new URL(`../fixtures/${name}.json`, import.meta.url), 'utf8').replace(/^\uFEFF/, ''))
async function feeds(page) {
  await page.clock.setFixedTime(new Date('2026-09-17T23:30:00Z'))
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.route('**/espn/**', (route) => {
    const url = new URL(route.request().url())
    if (url.pathname.endsWith('/schedule')) return route.fulfill({ json: fixture(url.searchParams.get('season') === '2015' ? 'schedule-2015' : 'schedule-2016') })
    if (url.pathname.endsWith('/summary')) return route.fulfill({ json: fixture('summary') })
    if (url.pathname.includes('/baseball/mlb/scoreboard')) {
      const day = url.searchParams.get('dates')?.slice(-2)
      return route.fulfill({ json: fixture(day === '17' ? 'today' : ['18', '19', '20'].includes(day) ? `weekend-${day}` : 'today') })
    }
    if (url.pathname.includes('/football/nfl/scoreboard') && url.searchParams.get('dates') === '20260920') return route.fulfill({ json: fixture('bears-weekend') })
    return route.fulfill({ json: { events: [], team: {} } })
  })
  await page.route('**/mlbstats/**', (route) => route.fulfill({ json: fixture('leaders') }))
}

for (const width of [390, 1280]) {
  test(`fan features preserve schedule links and saved progress at ${width}px`, async ({ page }, testInfo) => {
    await feeds(page)
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/?team=cubs&season=2016&tab=schedule')
    await page.getByRole('combobox', { name: /^Opponent/ }).selectOption('4')
    await expect(page.locator('.g-opp .name').first()).toContainText('White Sox')
    await page.getByRole('combobox', { name: /^Location/ }).selectOption('home')
    await expect(page.locator('.g-opp .name').first()).toContainText('vs')
    await page.getByRole('combobox', { name: /^Day/ }).selectOption('6')
    await expect(page.getByText('No games match these filters.', { exact: false })).toBeVisible()
    await page.getByRole('button', { name: 'Clear filters' }).click()
    const download = page.waitForEvent('download')
    await page.getByRole('button', { name: /^Export .* to calendar/ }).click()
    expect((await download).suggestedFilename()).toBe('cubs-games.ics')
    await page.getByRole('button', { name: '+ Collect ticket', exact: true }).first().click()
    await page.getByLabel('How did you follow this game?').selectOption('watched')
    await page.getByLabel('Your memory', { exact: false }).fill('Opening night with family')
    await page.getByRole('button', { name: 'Save ticket' }).click()
    await page.getByRole('button', { name: /My Games/ }).click()
    await expect(page.locator('.ticket')).toContainText('Opening night with family')
    await page.reload()
    await expect(page.locator('.ticket')).toContainText('I watched')
    await page.getByRole('checkbox', { name: /Spoiler-free/ }).check()
    await expect(page.locator('.ticket-memory, .ticket-score')).toHaveCount(0)
    await expect(page.locator('.tc-meta').first()).toHaveText('Record hidden')
    await expect(page.locator('.today-games b').first()).toHaveText('Score hidden')
    await page.getByRole('button', { name: 'Clubhouse', exact: true }).click()
    await page.getByRole('tab', { name: 'Heatmap', exact: true }).click()
    await expect(page.locator('.heat-tile.w, .heat-tile.l')).toHaveCount(0)
    await page.locator('.heat-tile').first().click()
    await expect(page.locator('.boxscore')).toHaveCount(0)
    await page.getByRole('button', { name: 'Reveal score', exact: true }).click()
    await expect(page.locator('.boxscore .linescore')).toBeVisible()
    await page.getByRole('tab', { name: 'Rivalries', exact: true }).click()
    await expect(page.locator('main')).toContainText('The Crosstown series')
    await page.getByRole('button', { name: 'Reveal series results' }).click()
    await expect(page.locator('main .summary')).toBeVisible()
    await page.getByRole('tab', { name: 'Showdown', exact: true }).click()
    await page.getByRole('button', { name: 'Reveal comparison' }).click()
    await expect(page.locator('.comparison-table')).toBeVisible()
    await page.getByRole('slider').fill('3')
    await expect(page.locator('.comparison-slider strong')).toHaveText('3')
    await expect(page.locator('.leader-card')).toHaveCount(2)
    await page.getByRole('button', { name: 'Daily Arcade', exact: true }).click()
    await page.locator('.answer-button').nth(dailyQuestion('2026-09-17').correctIndex).click()
    await expect(page.locator('.challenge-result')).toContainText('Correct!')
    await expect(page.locator('.achievement.earned')).toHaveCount(1)
    await page.reload()
    await expect(page.locator('.answer-button:disabled')).toHaveCount(4)
    await page.screenshot({ path: testInfo.outputPath(`arcade-${width}.png`), fullPage: true })
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
    await page.getByRole('button', { name: 'Chicago Tonight', exact: true }).click()
    await expect(page.locator('main .game-card')).toHaveCount(1)
    await page.locator('main').getByRole('button', { name: 'Weekend', exact: true }).click()
    await expect(page.locator('main .game-card').first()).toBeVisible()
    await expect(page.locator('main')).toContainText('Bears')
    await page.screenshot({ path: testInfo.outputPath(`tonight-${width}.png`), fullPage: true })
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width)
  })
}
